### ISSUE TITLE
Does map2 support hotstringing?

### ISSUE THREAD

**Issue by Drugoy** [shiro/map2#6]
By hotstrings I mean what AutoHotkey [means](https://www.autohotkey.com/docs/Hotstrings.htm), i.e. being able to type abbreviations and the script would replace it with the full form (like FBI -> Federal Bureau of Investigations).

Does map2 support that? If so - could you, please, provide an example?

**Comment by Drugoy** [comment]
Sorry, just figured that the docs only describe a way to use a key/hotkey to type a string, not a string to string, which is needed for hotstringing.

**Comment by shiro** [comment]
This is on the roadmap and will be added in a future version. Currently only single-key mappings are supported.

**Comment by Drugoy** [comment]
That's very nice to hear!
I don't honestly know if that'll be of any help to you, but... just in case you are out of good ideas about how things should work and what features/design they should have - I think it'd be very helpful to look at hot AutoHotkey does them.
I don't know if you are familiar with AutoHotkey, but that's a domain-specific language (DSL) that mainly has the same targets that your map2 seems to have.
It is very mature and is generally an awesome language, but since it works only on Windows and thus unavailable to me anymore - I have very high hopes that map2 will be able to be it's replacement under Linux.

p.s.: actually it even looks like you are familiar with it, because the resemblance of AutoHotkey code and map2 code is sometimes just uncanny.
p.p.s: I think there should be a community space around map2. What do you think? In the meantime I've registered `#map2` channel on IRC network on `irc.libera.chat` server and suggest you to come there if you like and maybe even add link into README pointing to that channel as community space. Or maybe you'd like to choose some different network (like gitter.im / zulipchat.com / anything else)?

**Comment by shiro** [comment]
Thanks for the encouraging words, I'm happy it's useful to someone.
I'm planning to add some social spaces after map2 is more mature and has a larger userbase, feel free to use the IRC channel for now, but I'm mainly using discord so I'll prob. use that and bridge it to matrix as well.

I'm currently working on a big rework which will deprecate the DSL entirely and use python for scripting since maintaining a custom language that is currently 3x slower than python on average and lacks most standard functions is not feasible.
I'll make sure to fork it into a separate repo in case people want to continue using the current language for the time being.

Feel free to open issues in case you have more suggestions, etc., however I'll prob. address most stuff in the new python-based release only.

**Comment by HarmonBlues** [comment]
:o

**Comment by HarmonBlues** [comment]
> Thanks for the encouraging words, I'm happy it's useful to someone. I'm planning to add some social spaces after map2 is more mature and has a larger userbase, feel free to use the IRC channel for now, but I'm mainly using discord so I'll prob. use that and bridge it to matrix as well.
> 
> I'm currently working on a big rework which will deprecate the DSL entirely and use python for scripting since maintaining a custom language that is currently 3x slower than python on average and lacks most standard functions is not feasible. I'll make sure to fork it into a separate repo in case people want to continue using the current language for the time being.
> 
> Feel free to open issues in case you have more suggestions, etc., however I'll prob. address most stuff in the new python-based release only.

Wait, there's a discord? Also what's DSL?

**Comment by shiro** [comment]
Not yet, I'll make one after the python update.
DSL = domain-specific language (currently we're using the custom map2 syntax, but it'll be deprecated in favor of using python)

**Comment by Drugoy** [comment]
IMO, Discord is <a href="https://news.ycombinator.com/item?id=29154216">a so-so choice</a>.
Maybe it's worth enabling Discussions for this repo right here on github? To enable them you just need to navigate to <a href="https://github.com/shiro/map2/settings#features">Settings</a> and scroll down to the end of the Features list and enable Discussions.

As for refactoring in favor of Python - I then hope that the result will be better than <a href="https://github.com/autokey/autokey/">AutoKey</a>, which is written entirely in Python, but never reached a decent quality level and is currently abandoned.

**Comment by shiro** [comment]
Thanks for the input, much appreciated!

The chat will be hosted on Matrix, which is decentralized and has no privacy issues. It is then mirrored over to discord for people like me who don't mind using it. I might also consider bridging it to IRC so everyone can talk to each other.

`AutoKey` not being great (API) and not working everywhere as `Autokey is X system based` made me make this project, so I'll try to keep it maintained and provide features that work and make sense. The huge difference is also that map2 is written in rust and only provides python bindings rather than being written in python itself, this keeps things fast.
I'll put out a beta release at some point so people can try it out and provide feedback if desired.

I also opened discussions, feel free to open topics there as well.

**Comment by HarmonBlues** [comment]
sounds good

**Comment by Drugoy** [comment]
@shiro
You have a big plan and I wish it plays out well and I'm looking forward to try it and provide some feedback / file bugs.
I don't want at all to sound pushy, but could you elaborate a bit on when do you plan to produce some MVP (minimum viable product) with python bindings?
I'm asking this simply because I want to start writing my "hotkey scripts" already, but at the same time I don't want to write the code that is to be obsoleted very soon.
So, could you give some assessment of the progress you've made so far?
Maybe you have a list of small targets/milestones/missing functionality, that needs to done before you could call the refactor a success and merge it into master?

**Comment by shiro** [comment]
If anyone wants to try out the new python branch, there's now a [preview announcement](https://github.com/shiro/map2/discussions/9). The API will prob. change, but it might be easier to write new scripts in python rather than port them over from `m2` later.

Hotstrining will continue to be tracked here, regarding other stuff please use GH discussions above.
